### ISSUE TITLE
why there is two types of admins ?

### ISSUE THREAD

**Issue by Surya-Git-hub** [Chandrkishor/Your-Thoughts-api#1]
Hi,
just casually checked your code, and this got me thinking that why there are three types of accounts when user registers e.g admin, administrator and normal user account ? what is the difference between admin and administrator ?

**Comment by Chandrkishor** [comment]
Hey Surya,
Thanks for reviewing my code, Please keep suggesting like that,
And for admin, yes, I will **remove** administrator.
